### ISSUE TITLE
请问一下，发布至 npm 后三个版本各自是使用的呢？

### ISSUE THREAD

**Issue by Fujihai** [Shimada666/vue-demi-sfc-component-template#1]
我在自己的 Vue2 项目中局部引入：
![image](https://user-images.githubusercontent.com/28208916/227406315-0baf88f3-9c54-42a6-9e76-9fd89c1cc038.png)
浏览器提示以下报错信息：
![image](https://user-images.githubusercontent.com/28208916/227406490-c8b19e05-8cb0-4c31-8aa2-e532489d4e10.png)

**Comment by Shimada666** [comment]
我的 demo 没做局部导出。你可以全局引入使用

```javascript
import TemplateComponent from 'vue-demi-sfc-component-template'

Vue.use(TemplateComponent)
```

**Comment by Fujihai** [comment]
> 我的 demo 没做局部导出。你可以全局引入使用
> 
> ```js
> import TemplateComponent from 'vue-demi-sfc-component-template'
> 
> Vue.use(TemplateComponent)
> ```

赞，全局引入就 OK 了😀。
![image](https://user-images.githubusercontent.com/28208916/227411562-3217b77f-60c0-44b8-b04d-cb273b5201dc.png)
